FROM matterlabs/external-node:2.0-v28.5.0

# Copy the local configs directory into the image
COPY configs /configs

# Set environment variables
ENV DATABASE_URL="postgres://postgres:notsecurepassword@postgres:5430/zksync_local_ext_node" \
    DATABASE_POOL_SIZE=10 \
    EN_HTTP_PORT=3060 \
    EN_WS_PORT=3061 \
    EN_API_NAMESPACES="eth,net,web3,zks,pubsub,en,debug" \
    EN_HEALTHCHECK_PORT=3081 \
    EN_PROMETHEUS_PORT=3322 \
    EN_ETH_CLIENT_URL="https://ethereum-rpc.publicnode.com" \
    EN_MAIN_NODE_URL="https://rpc.sophon.xyz" \
    EN_L1_CHAIN_ID=1 \
    EN_L2_CHAIN_ID=50104 \
    EN_PRUNING_ENABLED=false \
    EN_L1_BATCH_COMMIT_DATA_GENERATOR_MODE="Validium" \
    EN_EVM_EMULATOR_HASH="0x0000000000000000000000000000000000000000000000000000000000000000" \
    EN_DA_CLIENT="Avail" \
    EN_DA_AVAIL_CLIENT_TYPE="FullClient" \
    EN_DA_BRIDGE_API_URL="https://bridge-api.avail.so" \
    EN_DA_TIMEOUT_MS=20000 \
    EN_DA_API_NODE_URL="wss://mainnet.avail-rpc.com/" \
    EN_DA_APP_ID=102 \
    EN_DA_SECRETS_SEED_PHRASE="fuel index outdoor orbit pulp affair basket bus great afraid cabin also" \
    EN_STATE_CACHE_PATH="./db/ext-node/state_keeper" \
    EN_MERKLE_TREE_PATH="./db/ext-node/lightweight" \
    EN_SNAPSHOTS_RECOVERY_ENABLED=true \
    EN_SNAPSHOTS_OBJECT_STORE_BUCKET_BASE_URL="raas-sophon-mainnet-external-node-snapshots" \
    EN_SNAPSHOTS_OBJECT_STORE_MODE="GCSAnonymousReadOnly" \
    RUST_LOG="warn,zksync=info,zksync_core::metadata_calculator=debug,zksync_state=debug,zksync_utils=debug,zksync_web3_decl::client=error" \
    EN_CONSENSUS_CONFIG_PATH="/configs/mainnet_consensus_config.yaml" \
    EN_CONSENSUS_SECRETS_PATH="/configs/mainnet_consensus_secrets.yaml"
